### ISSUE TITLE
AzureAppConfigurationPush task always shows feature flags as requiring being added

### ISSUE THREAD

**Issue by brental** [Azure/AppConfiguration#791]
The AzureAppConfigurationPush task picks up feature flags from json config files and sets their key prefix and content type automatically during import. This is good but on subsequent push operations it shows that the feature flags need to be written again even if they exist in the app configuration with the same values already. This seems like it might be because the key and content type of the key values in the app configuration now differ from those in the json file so the push process thinks they need to be written again.

Would it be possible to have the logic to check whether feature flags have been imported take into account the logic for setting the key prefix and content type before checking? Or, is there a setting available to do this currently?

We are using the Default file content profile rather than the KVSet profile and using the Ignore-Match import mode.

EDIT: Is the source for the task available anywhere to look at?

**Comment by MaryanneNjeri** [comment]
Hello @brental I found there is a bug in terms of how we evaluate if the feature flag values in the store and the config file are equal, we'll work on a fix for that.  As a workaround to avoid  feature flags being written on subsequent push operations, might I suggest setting the "Exclude feature flags" option to true 
![image](https://github.com/Azure/AppConfiguration/assets/33903727/6b90cd0b-2032-498d-9156-cd6d0719a280)
this option specifies whether or not any feature flags in the provided configuration file will be pushed to the store. Please let me know if this helps

**Comment by brental** [comment]
Thanks @MaryanneNjeri, I will look into that setting. If that doesn't work as required then we can just leave it importing the feature flags each time until whenever the fix is released. It doesn't cause any major issues having them imported each time.

**Comment by MaryanneNjeri** [comment]
Hello @brental we have a new version AppConfigurationPush@6.2.0, with a fix for the issue. Please let me know if this helps resolve the issue.

**Comment by brental** [comment]
Thanks @MaryanneNjeri, I will try it out.

**Comment by CMarshall92Shawbrook** [comment]
Still getting an issue when pushing just a kv set that i have a locked feature flag I was assuming 6.2.0 would have fixed that any ideas or is this a seperate issue? need to be able to push kv sets with locked flags

**Comment by MaryanneNjeri** [comment]
Hello @CMarshall92Shawbrook what issue are you encountering?
